import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f5f5' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  scrollContainer: { flexGrow: 1, padding: 20, justifyContent: 'center' },
  header: { alignItems: 'center', marginBottom: 30 },
  iconWrapper: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#1976d2', justifyContent: 'center', alignItems: 'center', marginBottom: 16 },
  title: { fontSize: 28, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  subtitle: { fontSize: 16, color: '#666' },
  card: { backgroundColor: 'white', borderRadius: 20, padding: 24, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 8, elevation: 5 },
  label: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 8, marginTop: 12 },
  inputRow: { flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderColor: '#ddd', borderRadius: 12, paddingHorizontal: 12, height: 48, backgroundColor: '#fafafa', marginBottom: 12 },
  input: { flex: 1, marginLeft: 10, fontSize: 16 },
  inputSimple: { borderWidth: 1, borderColor: '#ddd', borderRadius: 12, paddingHorizontal: 12, height: 48, fontSize: 16, backgroundColor: '#fafafa' },
  row: { flexDirection: 'row', marginTop: 4 },
  button: { backgroundColor: '#1976d2', padding: 14, borderRadius: 12, alignItems: 'center', marginTop: 20 },
  buttonText: { color: 'white', fontSize: 16, fontWeight: 'bold' },
  linkText: { textAlign: 'center', marginTop: 20, color: '#1976d2', fontSize: 14 },
  appHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 15, backgroundColor: 'white', borderBottomWidth: 1, borderBottomColor: '#eee' },
  headerTitle: { fontSize: 18, fontWeight: 'bold', color: '#1976d2', flex: 1, marginLeft: 10 },
  userName: { fontSize: 14, color: '#666', marginRight: 10 },
  logoutBtn: { padding: 5 },
  tabBar: { flexDirection: 'row', backgroundColor: 'white', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#eee' },
  tabItem: { flex: 1, alignItems: 'center' },
  tabLabel: { fontSize: 11, color: '#999', marginTop: 4 },
  tabLabelActive: { color: '#1976d2', fontWeight: '600' },
  content: { flex: 1, padding: 20 },
  welcomeText: { fontSize: 22, fontWeight: 'bold', color: '#1976d2', marginBottom: 20 },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  statCard: { width: '48%', backgroundColor: 'white', padding: 15, borderRadius: 12, marginBottom: 15, borderTopWidth: 4, elevation: 2 },
  statValue: { fontSize: 32, fontWeight: 'bold', color: '#333', textAlign: 'center' },
  statTitle: { fontSize: 14, color: '#666', textAlign: 'center', marginTop: 5 },
  statHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  listHeaderTitle: { fontSize: 18, fontWeight: 'bold', color: '#1976d2' },
  addButton: { backgroundColor: '#1976d2', width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  listItem: { backgroundColor: 'white', padding: 15, borderRadius: 10, marginBottom: 10, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  itemTitle: { fontSize: 15, fontWeight: '600', color: '#333' },
  itemSubtitle: { fontSize: 12, color: '#666', marginTop: 3 },
  loader: { marginTop: 20 },
  modalContainer: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: 'white', borderRadius: 20, padding: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 20, textAlign: 'center' },
  modalInput: { borderWidth: 1, borderColor: '#ddd', borderRadius: 10, padding: 12, marginBottom: 12, fontSize: 15 },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 20 },
  modalCancel: { backgroundColor: '#e0e0e0', padding: 12, borderRadius: 10, flex: 1, marginRight: 10, alignItems: 'center' },
  modalSave: { backgroundColor: '#1976d2', padding: 12, borderRadius: 10, flex: 1, alignItems: 'center' },
  pickerLabel: { fontSize: 14, fontWeight: '600', marginBottom: 8, marginTop: 10 },
  pickerItem: { backgroundColor: '#f0f0f0', padding: 10, borderRadius: 8, marginRight: 10, minWidth: 100, alignItems: 'center' },
  pickerSelected: { backgroundColor: '#1976d2' },
});